### PR TITLE
Feature/zoom to country when country filter applied #435

### PR DESCRIPTION
**Pull request by main-tech**
Implement Zoom feature to country/s selected and resolve some type errors in 'review form test'

### CODE REVIEW

**Comment by shishi5089** [comment]
Hello Mandela,
Change the method used in the unit tests to it() instead of test() to maintain consistency in the code

**Review by shishi5089 — COMMENTED** [review]
Everything else looks good. Just the small fix and it'll be ready for merge

**Review by gituman — COMMENTED** [review]
Mandela can you move the use effect from line 177 to 196 to either point utils and export it so that it matches the other use effects on mapv2. Like store the method in a const and call the const in the use effect like the update legend for species use effect

**Comment by main-tech** [comment]
@gituman  I did implement your recommendations you can re-review the pull request

**Review by shishi5089 — APPROVED** [review]

**Pull request merged**
